### ISSUE TITLE
[Website Bug]: search pagination not working property (api level)

### ISSUE THREAD

**Issue by 0xMALVEE** [unicorn-utterances/unicorn-utterances#1031]
### Description

Hey,
The search pagination in here is not utilizing api it's just showing pagination after getting all items not like getting 6 posts per endpoint calling. maybe should have had something like https://unicorn-utterances.com/api/search?query=react&page=2 in the actual api and not in the frontend. not sure what's the point of having that in the frontend only dosen't decrease api/db load tho. 
![image](https://github.com/unicorn-utterances/unicorn-utterances/assets/35369563/e3fb4746-5eb9-4fcc-aaca-0c8f55d607de)

### Minimal Reproduction

search endpoint 

### Exception or Error

not a broken error but theory behind the pagination in the frontend and not in api level doesn't benifit from anything I think.

**Comment by crutchcorn** [comment]
Closing as this is engineered as-intended. We have no database and our traffic size for search is tiny.
