### ISSUE TITLE
[Website Bug]: Cancelling search results removes controls & causes back navigation bug

### ISSUE THREAD

**Issue by meows** [unicorn-utterances/unicorn-utterances#1041]
### Description

When you visit this search experience:

https://unicorn-utterances.com/search?searchQuery=react&filterAuthors=crutchcorn&filterTags=angular

- And then you `(X)` the search result, the filters will disappear from screen and there's no obvious way to get them back.
- Pressing back from this state changes the URL but won't do anything for a few tries.
- Typing the same search query will remove the filters.

**Comment by fennifith** [comment]
Opened #1061 for the navigation bug. The filters disappearing is currently the intended behavior, as described in #861 - feel free to comment there if you have any thoughts on it :)
