### ISSUE TITLE
[Proposed Post]:  Javascript Math

### ISSUE THREAD

**Issue by JericoGit** [unicorn-utterances/unicorn-utterances#1042]
### Proposed topic title:

Javascript: Mathematical uses.

### Topic description:

I would like to see an article on JavaScript mathematical uses and further ways to extend the math library and features that are already. in JavaScript

### Link to existing draft:

https://docs.google.com/document/d/1xYUutd7gnvoXgKuw6jME-fcrH2Lcrp0vf8RUJCsmXoo/edit Mabye my draft can help.

**Comment by crutchcorn** [comment]
Any chance you'd be interested in writing this for our site? 😄 Sometimes the best learning is by teaching!

**Comment by JericoGit** [comment]
@crutchcorn maybe I talked to my friend about his UU thing after I posted this and might not want to get into it. So will see. I published this on my site for now. https://jericogit.github.io/Jerico/Articles/math-js.html If you do want me to right though I will I just need to know rules and stuff, and where I should post my stuff.

**Comment by JericoGit** [comment]
I read the contributing guide and looked through some code.  I figured screw it and submitted my article with some additions and deletions. I submitted the article through pull requests and am hoping you like it. Read it and tell me what you think.

**Comment by crutchcorn** [comment]
Closing, as you wrote our article on the topic! 🎉 It should be live momentarily!
