### ISSUE TITLE
Internal links need to be made into absolute links (`![Some link](/posts/other)` -> `![Some link](https://unicorn-utterances.com/posts/other)`)

### ISSUE THREAD

**Issue by MateuszWasik** [unicorn-utterances/unicorn-utterances#1050]

**Comment by MateuszWasik** [comment]
As discussed on the Discord channel, this task has been done already by @fennifith :) 

So for now I will mark it as done, but if ever this topic comes back (edge cases) I will look into it. What do you think @crutchcorn ?

**Comment by crutchcorn** [comment]
Sounds good to me!
