### ISSUE TITLE
[Website Bug]: Get through FFG and check if links are working

### ISSUE THREAD

**Issue by MateuszWasik** [unicorn-utterances/unicorn-utterances#1052]
### Description

Hey there! So, I was reading through Chapter 2 and came across a link that's not working properly. It got me thinking that we might run into the same hiccup in other chapters too. So, I think it's a good idea to go through all the FFG chapters and give those links a double-check to make sure everything's running smoothly.

**Comment by MateuszWasik** [comment]
@crutchcorn I need some assistant here. In Preface chapter https://unicorn-utterances.com/posts/ffg-fundamentals-preface you were providing links for Xbox website, Voice website, Messages site etc.

Those links are not correct since there is no such address like `https://www.madewithangular.com/sites/xbox`.

I would like to know if that was on purpose, should we leave it that way or remove the links entirely?

**Comment by crutchcorn** [comment]
@MateuszWasik let's remove those links entirely. They worked at some point, but no longer do

**Comment by MateuszWasik** [comment]
@crutchcorn Done!
