### ISSUE TITLE
[Website Bug]: "View This Post on Github" link broken (in some cases?)

### ISSUE THREAD

**Issue by joezimjs** [unicorn-utterances/unicorn-utterances#1072]
### Description

I was on https://unicorn-utterances.com/posts/ffg-fundamentals-accessing-children and clicked the link at the bottom of the page to "View This Post on Github" and it took me to https://github.com/unicorn-utterances/unicorn-utterances/tree/main/content/blog/ffg-fundamentals-accessing-children/index.md which was a 404

### Exception or Error

404

**Comment by alejandrocuba** [comment]
This issue is also reproducible in other blog posts across the site, not just in FFG content.
