### ISSUE TITLE
[Website Bug]: Broken link to missing "Content Reference" chapter

### ISSUE THREAD

**Issue by bk7312** [unicorn-utterances/unicorn-utterances#1080]
### Description

In [Part 6](https://unicorn-utterances.com/posts/ffg-fundamentals-transparent-elements) and [Part 8](https://unicorn-utterances.com/posts/ffg-fundamentals-element-reference) of the framework field guide, there is a broken link to a missing "Content Reference" chapter. See links to the code below:

https://github.com/unicorn-utterances/unicorn-utterances/blob/13c18d1c70775f87d8bdc53a02383ca0ac12aea1/content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-transparent-elements/index.md?plain=1#L438

https://github.com/unicorn-utterances/unicorn-utterances/blob/13c18d1c70775f87d8bdc53a02383ca0ac12aea1/content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-element-reference/index.md?plain=1#L744

**Comment by crutchcorn** [comment]
Thank you for reporting this and the other stuff! You've been intensely helpful!
