### ISSUE TITLE
Google TalkBack accessibility issues

### ISSUE THREAD

**Issue by evelynhathaway** [unicorn-utterances/unicorn-utterances#131]
Google TalkBack on Android v10 and Chrome v81 Dev with the `default` navigation setting:

- Reads the following as [`use attributes`](https://user-images.githubusercontent.com/38994283/71550139-3d57be00-297e-11ea-912a-c827d9d7d393.png)
	- Is this an upstream bug or can this be patched on our side?
```
[use `data` attributes](http://example.com)
```

- [Reads the filter select tool in a very verbose manner](https://youtu.be/2A1dUINIAVs)
	- What's the intended behavior for this?

**Comment by crutchcorn** [comment]
"This video is private" - I'm unable to see it

**Comment by evelynhathaway** [comment]
Sorry, it was marked as a draft in YouTube It's up now

**Comment by crutchcorn** [comment]
I think the `use attributes` issue is a bug within TalkBack:

![MacOS VoiceOver reading the sentence properly](https://user-images.githubusercontent.com/9100169/74554727-0c702000-4f0f-11ea-8a83-cf6429df3b46.png)

Looking into it further, it doesn't seem we're doing anything wrong in `a` tags hosting a `code` tag:

![MDN showing that "Flow content" is permissible children and that `code` is permissible flow content](https://user-images.githubusercontent.com/9100169/74554868-5a852380-4f0f-11ea-8744-62e43c65f652.png)

As for the filter button, I think that should be an easy fix

**Comment by crutchcorn** [comment]
I was able to touch base with Google Disability Support Chat. I informed them of this bug and linked them to this GitHub issue. I was reassured that they'd take a look at the issue and email me back. I'll report and updates here. Amazing find @evelynhathaway !

**Comment by crutchcorn** [comment]
I've got the following response:

>Hi Corbin,
> Thanks for reaching out to Google Disability Support.
>
>Thanks for your patience while I tested this. Firstly, I was able to replicate this on the Chrome Dev version with a Pixel 3a with TalkBack & Samsung S10 with Voice Assistant (the test devices I used for this case). When I tested on the Chrome Native app 79.0 and Firefox Native app 68.5 I was not able to replicate the issue. 
>
>This leads me to believe it is an issue isolated to just the Chrome Dev app. With this being said I'd recommend that you and the original poster of this report a bug to the Chromium team. I've added a link below for more information on that. 
>
>- [Bug Life Cycle and Reporting Guidelines - The Chromium Projects](https://www.chromium.org/for-testers/bug-reporting-guidelines)
>
>I appreciate you bringing this to our attention and I'm happy that I was able to isolate the issue at least. If you have any questions regarding Google accessibility and assistive technologies, feel free to reply back to this email!

**Comment by crutchcorn** [comment]
@evelynhathaway wanna do the honors? :)

**Comment by evelynhathaway** [comment]
As an update, I the issue with code in links is fixed. 🎉
