### ISSUE TITLE
Fix homepage logo margin on small breakpoint

### ISSUE THREAD

**Issue by sarsamurmu** [unicorn-utterances/unicorn-utterances#145]
On the homepage, the logo has unnecessary margin-right on small breakpoint. That should be fixed.

**Comment by crutchcorn** [comment]
![Screenshot showing the margin on the left](https://user-images.githubusercontent.com/9100169/74596028-5be14980-4ffe-11ea-9ac3-3d59e06af0e2.jpg)
An example of what this is talking about. The logo is too far to the left

**Comment by MDutro** [comment]
This one should be fixed. Would you like me to do a pull request now or wait until I've tackled a few more issues?

**Comment by crutchcorn** [comment]
We try to keep pull requests on a per-issue basis. (1 PR for 1 fix/feature). Tends to be the best course of action for tracking. Go ahead and make the PR whenever you're ready :)

**Comment by sarsamurmu** [comment]
Closing the issue as the bug is fixed.
