### ISSUE TITLE
Oswald font isn't fetched by gatsby-plugin-prefetch-google-fonts

### ISSUE THREAD

**Issue by evelynhathaway** [unicorn-utterances/unicorn-utterances#171]
See: https://github.com/escaladesports/legacy-gatsby-plugin-prefetch-google-fonts/issues/27

Possibly fork the package or use an existing fork if no replacement is found. Archivo looks nice for now.

**Comment by crutchcorn** [comment]
I vote that we fork it and then maintain the package ourselves. There's already precedent behind publishing NPM packages related to UU. I even plan on breaking out some of our existing plugins to NPM packages down the line.

**Comment by evelynhathaway** [comment]
It may be easier or more performant to not use the plugin as well. We should also look into why the plugin was deprecated and if the issue is upstream with the typekit library it's based on.
