### ISSUE TITLE
Generic profile links

### ISSUE THREAD

**Issue by fennifith** [unicorn-utterances/unicorn-utterances#23]
The current [unicorn structure](../blob/master/src/data/unicorns.json) only supports links for "socials", such as Twitter or GitHub. I'd like for this to support generic links of all types, such as personal websites, Mastodon or other fediverse accounts, LinkedIn profiles, GitLab accounts, etc. - but that list would just keep growing.

Rather than support all kinds of links in this field, it might be better to treat it as an array of links which can have either a specific or generic type associated with them (which is then used to determine the icon / other future uses in the site).

I do agree that the number of links should be limited in some way to preserve the style of the profile layout, but the type of links that can be included should not be restricted by it. While Twitter/GitHub are often used for their purposes, I don't think that this project should specifically endorse their use over competing platforms, nor should it prevent people without those platforms from taking advantage of this functionality.

Proposed example:
```json
{
    "links": [
        { "type": "twitter", "at": "fennifith" },
        { "type": "website", "name": "Personal Site", "url": "https://jfenn.me/" }
    ]
}
```

Possible link types that could be added (that aren't possible with the current structure):
- website (for generic "links" that might not mean anything)
- profile (for abstract social media links or portfolios)
- fediverse (federated blogs or social media under an acknowledged protocol)
- mastodon (mastodon servers / accounts)

**Comment by crutchcorn** [comment]
I like this idea generally, but my question would be the following:

How do we want to do the icons? I think we should keep consistent with our icons we currently have (that our @unicorn-utterances/design team develops). That said, I have enabled the ability to add an arbitrary website to #14. However, the "arbitrary website" currently only says "website". I'm sure we could minimally add a "name" field to the website in a small follow-up story

**Comment by fennifith** [comment]
Given that we now have a generic "website" link, think this could be closed by just supporting a few more [link types](https://github.com/unicorn-utterances/unicorn-utterances/blob/main/src/types/UnicornInfo.ts), some of which we [already have icons for](https://github.com/unicorn-utterances/unicorn-utterances/tree/uwu/src/icons):

- mastodon
- threads
- youtube

...and I can't think of any others that would be hugely relevant. Suggestions welcome, though :)
