### ISSUE TITLE
Allow a post to have multiple authors

### ISSUE THREAD

**Issue by adueppen** [unicorn-utterances/unicorn-utterances#25]
Considering the collaborative nature of this project, I'm sure that there will be some blog posts written by more than 1 person. At the moment it only seems to be possible for there to be a single author on a post, so it would be nice if the post format could have a list of authors instead. We will need to consider the UI for this as having multiple profile pictures on the homepage wouldn't work very well at the moment.

**Comment by adueppen** [comment]
[This](https://github.com/gatsbyjs/gatsby/issues/3199) might be a useful resource to use

**Comment by crutchcorn** [comment]
While I'm far from pushing others away from resources - I'd give word of caution against relying too heavily on another's implementation in Gatsby as we have our own implementation which isn't exactly standard.

The gist of what would need to be changed is:

`author` to be turned into an array on each existing post and changed the key to `author` (the ids can stay the same as they will map properly

every instance we're using the `author` key to update to `authors` (the GraphQL fragment can be updated for `PostInfo` and it will propagate - just need to change the JS after that point)

**Comment by crutchcorn** [comment]
As for design, let's ask @tommyemo what his thoughts on this are

**Comment by adueppen** [comment]
This will require some CSS changes but if we want something nice and simple I could see just having the 2 profile pictures stacked vertically. At the moment there's usually plenty of space as long as the blurb is long enough.

**Comment by tommyemo** [comment]
i'm just realizing now how fucked up the author pic size was before because...i don't know why

**Comment by tommyemo** [comment]
by adjusting the profile pics to 96x96 (you know, actually on the grid, Tom), we could stack the profile pics diagonally at 60x60 with some overlap and i think this would work. on mobile we can stack them vertically like Alex suggested

![image](https://user-images.githubusercontent.com/7970209/62878782-663d2680-bcef-11e9-92bd-6d7ded5b14e9.png)

https://www.figma.com/file/di3zKgJCj264nqN9g3UCSLwP/crutchcorn-%E2%80%93-unicorn-utterances?node-id=309%3A1946

**Comment by tommyemo** [comment]
and on mobile where the two names don't require a line break, we can center the metadata on the group of profile pics
![image](https://user-images.githubusercontent.com/7970209/62879106-0430f100-bcf0-11e9-9306-534649331cb9.png)

**Comment by crutchcorn** [comment]
From a programatic standpoint, it would be easiest/best to always center the metadata on mobile.

@adueppen take a look at `flex-align: center` w/ media breakpoints (be sure to use our breakpoints defined in SCSS)

**Comment by tommyemo** [comment]
np bb
