### ISSUE TITLE
Migrate away from `react-pose`

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#268]
https://www.npmjs.com/package/react-pose

`react-pose` is depreciated. We should migrate the two components we use it for to another animation package

**Comment by skatcat31** [comment]
my suggestion would be react reveal or framer motion. Both are pretty easy to use and I'm pretty certain it should be easy to see how to replace the component...

**Comment by crutchcorn** [comment]
So I can probably figure out how to change the timing, but I'm working on migrating from `pose` to `framer-motion` and I noticed a different behavior,

Before:

![posed](https://user-images.githubusercontent.com/9100169/117091812-53fbeb00-ad11-11eb-8d6c-d6f21865000f.gif)

After:

![framer](https://user-images.githubusercontent.com/9100169/117091819-58c09f00-ad11-11eb-9a46-119f6332d436.gif)

**Comment by skatcat31** [comment]
I'm not sure that's a deal-breaker though?

**Comment by crutchcorn** [comment]
It's totally not - and I figured out how to make them match a bit better. Just thought it was funny more than anything
