### ISSUE TITLE
OceanBit Disclosure

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#279]
Hi all. Just for the sake of transparency, and to align with our statement of ethics, I figured I'd disclose my (and UU's) relationship to OceanBit.

The long-short of it is: I am the founder of both. UU isn't a company OFC, but OceanBit is a legal LLC.

OceanBit is currently sponsoring UU by paying for hosting fees, domain costs, our Google Domain instance (for email logic), and a few odds and ends here and there.

The only reason OceanBit is sponsoring UU is to keep the site running smoothly and allow for good content to reach others. I don't intend to add ads to OceanBit to the site (outside of the small "sponsor" banner, but that's frankly mostly for transparency), don't plan on adding additional control to the site, or limiting the types of content posted to the site for OceanBit's posterity.

OceanBit's website does include [a blog section](https://oceanbit.dev/blog), and I _may_ cross-post content from there to this site. However, if I do it **must** be primarily about the technical underpinnings of something we're doing. I want to share useful content for folks uninterested in OceanBit, but will not be posting product or company announcements here.

Please feel free to raise any concerns or comments regarding this relationship

**Comment by crutchcorn** [comment]
Closing to avoid cluttering open issues.

This does not mean the conversation is closed off to others or unrelated. Please feel free to comment anything related

**Comment by ThorondorManwe** [comment]
**Spanish Translation**

# Reconocimiento: OceanBit
_____

Hola a todos. Solo por el bien de la transparencia y para alinearnos con nuestro código de ética, pensé en revelar mi relación (y la de UU) con [OceanBit](https://oceanbit.dev/).

En resumen: soy el fundador de ambas. UU no es una empresa OFC, pero OceanBit es una LLC legal.

En la actualdiad OceanBit está patrocinando a UU por medio del pago de cuotas de hosting, los costos del dominio, nuestra instancia de Google Domain (para la lógica del email), y algunas cosas pequeñas aquí y allá.

La única razón por la que está patrocinando a UU es para mantener el sitio funcionando sin problemas y así permitir que el buen contenido llegue a otros. No busco añadir anuncios de OceanBit al sitio (fuera del pequeño banner de "patrocinador" pero esto es principalmente por la transparencia), no planeo agregar control adicional al sitio, o limitar los tipos de contenido publicado en el sitio para la posteridad de OceanBit.

El sitio de OceanBit tiene una [sección de blog](https://oceanbit.dev/blog), y yo *podría* publicar contenido de allí en este sitio. Sin embargo, si lo hago **debe** ser principalmente acerca de los fundamentos técnicos de algo que estemos haciendo. Quiero compartir contenido útil para personas que no estén interesadas en OceanBit, pero no publicaré ni productos ni anuncios de la compañía aquí.

No dudes en plantear cualquier inquietud o comentario sobre esta relación.
