### ISSUE TITLE
CoderPad Disclosure

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#280]
Hi all. Just for the sake of transparency, and to align with our statement of ethics, I figured I'd disclose my relationship to [CoderPad](http://coderpad.io/).

At time of writing, I am working for CoderPad as a Developer Relations Specialist. One of my job responsibilities is to create content for CoderPad. Recently, I have been cross-posting some of my blog content from [CoderPad's blog](https://coderpad.io/blog/) that I have written for the company.

I am cross-posting for two reasons:

- Sharing useful/interesting content for others
- Personal work archival

However, I will _never_ cross-post content that does not provide value outside of the context of promoting CoderPad. This means that any of the docs work I'm doing or product-specific announcements will not be found on UU's site.

Likewise, we would love to encourage others to cross-post content they've written elsewhere (under similar disclosure and moderation rules). We don't want this to unfairly advantage any particular author/working relationship - myself included.

-----------

On the note of the idea of CoderPad's control over UU - they don't.

While yes, you could make an argument that they do _technically_ provide funding for the site - it's only by the transative property of OceanBit's funding of the site (#279) and me funding OceanBit (as of time of writing). Outside of this, CoderPad does not provide any funding to the site, nor the community. 

Further, CoderPad does not have editorial control over original content posted on UU, nor do they control any part of the website or community.

----------

Please feel free to raise any concerns or comments regarding this relationship

**Comment by crutchcorn** [comment]
Closing to avoid cluttering open issues.

This does not mean the conversation is closed off to others or unrelated. Please feel free to comment anything related

**Comment by crutchcorn** [comment]
Full disclosure: I've left CoderPad as my daily employment. I'm still consulting for them in regards to technical reviewing and guest blog post authoring, however, so you may still see posts "sponsored" by CoderPad on the site.

**Comment by crutchcorn** [comment]
Another update: I have since halted my consulting contract with CoderPad.

**Comment by ThorondorManwe** [comment]
**Spanish Translation**

# Reconocimiento: CoderPad

Hola a todos. Solo por el bien de la transparencia y para alinearnos con nuestro código de ética, pensé en revelar mi relación con [CoderPad](https://coderpad.io/).

Al momento de escribir esto estoy trabajando para CoderPad como Especialista en Relaciones con Desarrolladores. Una de mis responsabilidades es escribir contenido para CoderPad. Recientementehe he estado publicando en mi blog contenido que he escrito en el blog de la empresa.

Estoy publicando contenido de CoderPad por dos razones:

- Compartir contenido útil/interesante para otros
- Archivo de trabajo personal

Sin embargo, nunca publicaré contenido de esa compañía que no provea otro valor además de promover a CoderPad. Lo que significa que cualquier trabajo de documentación que estoy haciendo o anuncios específicos de productos no se encontrarán en el sitio de UU.

De igual forma, nos gustaría animar a otros a publicar contenido que hayan publicado en otro lugar (con las mismas reglas de divulgación y moderación). No queremos que esto sea una ventaja injusta para cualquier relación autor/trabajo - incluyéndome.

---

En cuanto a la idea que de CoderPad tiene control sobre UU - ellos no lo tienen.

Si bien podrías argumentar que ellos técnicamente están financiando el sitio - es solo por la propiedad transativa de la financiación del sitio por parte de OceanBit ([#279](https://github.com/playfulprogramming/playfulprogramming/issues/279)) y a que yo financio OceanBit (al momento que escribo esto). Además de esto, CoderPad no proporciona ningún financiamiento al sitio ni a la comunidad.

Además, CoderPad no tiene control editorial sobre el contenido original publicado en UU, y tampoco controla ninguna parte del sitio o de la comunidad.

---
No dudes en plantear cualquier inquietud o comentario sobre esta relación.

**Actualización del 20 de agosto del 2022**
Reconocimiento completo: Dejé CoderPad como mi trabajo diario. Sin embargo, estoy realizando consultoría para ellos en lo que respecta a la revisión técnica y la redacción de publicaciones de blogs invitados, por lo que es posible que aún veas publicaciones "patrocinadas" por CoderPad en el sitio.

**Actualización del 7 de diciembre del 2022**
Otra actualización: he suspendido mi contrato de consultoría con CoderPad.
