### ISSUE TITLE
The Polyglot Developer Disclosure

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#281]
Hi all. Just for the sake of transparency, and to align with our statement of ethics, I figured I'd disclose my (and UU's) relationship to [The Polyglot Developer](https://www.thepolyglotdeveloper.com/).

The Polyglot Developer is run by [Nic Raboy](https://www.nraboy.com/), a good friend of mine.

Towards the start of the blog, Nic asked if we wanted to share our logos on our respective blogs. The goal here being cross-linking for the sake of SEO. We agreed, moved forward, and now share our logos as sponsors of one another.

We think this makes sense, especially as Nic is an active member of our community and helps share information with us whenever we need.

That's all - no other control, finances, or impacts are shared by this sponsor spot

Please feel free to raise any concerns or comments regarding this relationship

**Comment by crutchcorn** [comment]
Closing to avoid cluttering open issues.

This does not mean the conversation is closed off to others or unrelated. Please feel free to comment anything related

**Comment by jahirfiquitiva** [comment]
Translated to Spanish at [Reconocimiento: The Polyglot Developer](https://github.com/unicorn-utterances/unicorn-utterances/issues/401)

**Comment by crutchcorn** [comment]
Thank you @jahirfiquitiva! 

Any way you could post that translation here instead? :)

**Comment by jahirfiquitiva** [comment]
**Spanish Translation**

Reconocimiento: The Polyglot Developer

Hola a todos. Solo por el bien de la transparencia y para mantenernos alineados con nuestra declaración de ética, pensé en revelar mi relación (y la de Unicorn Utterances) hacia [The Polyglot Developer] (https://www.thepolyglotdeveloper.com/).

Polyglot Developer está dirigido por [Nic Raboy](https://www.nraboy.com/), un buen amigo mío.

Cuando iniciamos con blog, Nic preguntó si queríamos compartir nuestros logotipos en nuestros respectivos blogs. El objetivo aquí es el enlace cruzado para mejorar el SEO. Estuvimos de acuerdo, avanzamos y ahora compartimos nuestros logotipos como patrocinadores mutuos.

Creemos que esto tiene sentido, especialmente porque Nic es un miembro activo de nuestra comunidad y ayuda a compartir información con nosotros cuando lo necesitamos.

Eso es todo: este anuncio de patrocinador no comparte ningún otro tipo control, finanzas o impactos.

No dudes en informar cualquier inquietud o comentario con respecto a esta relación.

Este issue puede estar cerrado para evitar una gran lista de issues abiertos. Sin embargo, no significa que la conversación se cierre a otros o que no esté relacionada.
