### ISSUE TITLE
CD Facing 503 "Slow Down" errors occationally

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#292]
Occasionally, our CD builds hit a 503 "slow down" from DO spaces:

https://github.com/unicorn-utterances/unicorn-utterances/runs/4656310090?check_suite_focus=true

The S3 Sync command doesn't mention a timing thing anywhere in their docs:

https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html

https://github.com/jakejarvis/s3-sync-action

**Comment by evelynhathaway** [comment]
DigitalOcean recommends an exponential backoff algorithm in response to rate limiting. AWS CLI for S3 appears to implement a solution that should work with DO Spaces, but maybe we're running into the max retries before we backoff enough for the amount of files we're pushing. I'll continue to look into this.

AWS CLI Docs: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-retries.html

**Comment by evelynhathaway** [comment]
This should be properly fixed now from #295. I will re-open if it still occurs.
