### ISSUE TITLE
Tags above article titles are not hyperlinks

### ISSUE THREAD

**Issue by gitname** [unicorn-utterances/unicorn-utterances#302]
When I click on the tags above the article titles, nothing happens. I had assumed clicking one would take me to a list (i.e. index) of all articles tagged with that same tag.

![image](https://user-images.githubusercontent.com/7143133/148668493-e5ec7946-365a-46e0-a6ea-669e7846f068.png)

This behavior may be by design/intentional. I reported this to one of the developers of this blog and he suggested that I file an Issue for it.

Blog is looking good! 👏

**Comment by crutchcorn** [comment]
Actually - I was mistaken with this one - this one is expected behavior! Sorry for the confusion!
