### ISSUE TITLE
"Articles" text in a specific author's page is plural when only one article exists

### ISSUE THREAD

**Issue by Rodentman87** [unicorn-utterances/unicorn-utterances#304]
Visible here: [https://unicorn-utterances.com/unicorns/maisydino](https://unicorn-utterances.com/unicorns/maisydino)

Fairly minor bug, may also apply to the "words" text but I don't think that's likely to ever hit exactly 1.

**Comment by bobrossrtx** [comment]
I will try and fix this right away 😃

**Comment by bobrossrtx** [comment]
Fixed the issue
![Screenshot 2022-01-16 at 00 57 43](https://user-images.githubusercontent.com/73446766/149643239-0453cc0d-91cc-47b7-b971-f2a01876b00e.JPG)

**Comment by bobrossrtx** [comment]
There is a new pull request for the fix, as the other one was before the rebase.

**Comment by crutchcorn** [comment]
Fixed by @bobrossrtx !
