### ISSUE TITLE
Enable generation of full-text license file on a per-author/license basis

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#35]
While we currently (#32 ) have the ability to display a license at the bottom of a post, we do not currently have a license file generated for that author and the license for that file. This seems like an oversight we could solve fairly easily. 

My suggested API would be the following:

In our `licenses.json` file, we add a `"copy"` property that includes a reference to a file of the full text of the license in question.

This file will include interpolation compatability to fill it with the `frontmatter.author` properties to fill the text of that license on compile-time ([using `onPostBuild` or something like it](https://spectrum.chat/gatsby-js/general/generating-json-file-with-gatsby~c539d9a7-970c-4a52-ac79-18a51f254537?m=MTUyMzk5NjI5Njk0Mg==)) and create a consistent URL structure for such (ala `unicorn-utterances.com/licenses/crutchcorn--cc-by-nc-sa-4.md`).

For future development, we could potentially even introduce `301` redirects using [our NGINX rules](https://github.com/unicorn-utterances/unicorn-utterances/blob/master/config/redirects_unicorn-utterances.com) for each of the posts to make `https://unicorn-utterances.com/posts/uttering-hello-introduction-post/LICENCE.md` redirect to the expected license

**Comment by fennifith** [comment]
Closing per comments from @crutchcorn. I think this isn't necessary to automate, and most of our post licenses (creative commons) only require the current image/link to apply to the post content.
