### ISSUE TITLE
Unique Link for Contributors

### ISSUE THREAD

**Issue by kaleem68** [unicorn-utterances/unicorn-utterances#380]
### Problem
https://unicorn-utterances.com/about#contributors

As in the above link, when the contributors list grows (it already has), it would require a scroll to find contributors. A better approach would be to generate a unique link that targets specific contributors within this link https://unicorn-utterances.com/about#contributors.

### Motivation
- A unique link for each contributor within the contributions list makes it easy to share the work, especially if you want to share it in public.

### Solution
> This link will be there as it is: https://unicorn-utterances.com/about#contributors
#### New Additions
> A link to each contributor will be generated - which, when opened, will target the page to the contributor. Here is an example link for contributor Kaleem: https://unicorn-utterances.com/about#contributors-kaleem

**Comment by crutchcorn** [comment]
We discussed this shortly in Discord:

Me:
> Worth highlighting:
>
>Each contributor has a dedicated page that's generated for them
>
>https://unicorn-utterances.com/unicorns/kaleem

@kaleem68:
> I have seen that but i think both serve different purposes. I'm raising an issue happy to discuss.

I then discussed with @kaleem68 on Discord VC what he meant by "difference purposes", and he explained that:

- The about us page shows non-blogging contributions list
- The unique "unicorns" pages are too blog-centric, despite UU being more than a blog
     - These  pages show "No results could be found, you might try making your search or filter less restrictive" if not a blog author

I 100% agree with these points.

That said, I think the better course of action isn't to add more linking to the about us page (which actually has potential A11Y/UX issues), but instead **I'd like to improve the unicorns "about" us page to be more representative of the contributors by**:

- Add contributor role tags
- Dynamically hide the blog list when unicorn has no blog posts
- Add translated blog posts to translator contributions

I'd love to hear the community's feedback on this idea, and if a few folks like it I'll ask some of our design friends to make a new design for the "unicorns" page that incorporates these changes

**Comment by kaleem68** [comment]
The design of this page https://unicorn-utterances.com/unicorns/kaleem can be done along with the enhancement in this https://unicorn-utterances.com/about#contributors. Both can be done 

I'm curious what other people think about the contributors mentioned here. https://unicorn-utterances.com/about#contributors

**Comment by crutchcorn** [comment]
Both _can_ be done, but I challenge _why_ they need to both be done.

The reason I'm hesitant to update the about us page to include links to individual people is because:

- We'd then have to include a way to copy the link to individual people for each contributor. This would make the UX cluttered
- It's brittle, if we change the about us URL, then all of the links to the users would break. We also can't 301 or 302 redirect the pages

This is why I'd _rather_ change the individual pages instead of the contributor pages

**Comment by william-lohan** [comment]
The updating the page for the individual to display based on 'if has blogs' or role makes more sense and more "what the page is for", adding a custom anchor or fragment to the about us seems like trying to do too much with the page.

**Comment by Hopelezz** [comment]
## Proposing 

- `If has blog`  show badge 🦄
- `if has contribute` shows badge 🚧
- `if has both` shows both badges 🦄🚧

You can then set different badges for different things. I mean you have some awesome unicorn emotes... Could just use those.

## As for the main topic

@crutchcorn, If the page is fragile then busting it up isn't the move. I suggest the time be better spent making the page more stable or some other stability fixes.  

There's also a conversion in the works. Might be worth revamping the about page with components. Adding in that stability, modularity, flexibility, and a few additional features.

**Comment by crutchcorn** [comment]
Closing this issue in favor of improving non-blog author contributor pages, like so:

https://github.com/unicorn-utterances/unicorn-utterances/issues/384

Work is actively being done here! :D
