### ISSUE TITLE
Migrate away from Google Analytics

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#383]
We're currently using Google Analytics, but our version of GA will be sunset in 2023. 

On top of that, we want to avoid GA for privacy reasons but want to keep some type of analytics for guidance purposes 

We're comfortable paying for this analytics platform if needed, or I can self-host it on my local server at home.

**Comment by AlexChadwickP** [comment]
https://matomo.org/ seems like a decent alternative with a focus on data privacy? They have both a paid option and a free self-hosted option as well. I've personally never used it but it seems to be fairly popular amongst people that are looking for google analytics alternatives.
