### ISSUE TITLE
Accessibility: Filter List doesn't scroll. 

### ISSUE THREAD

**Issue by Hopelezz** [unicorn-utterances/unicorn-utterances#389]
## Problem:

Then arrow keying through the filter list. The list doesn't scroll
![image](https://user-images.githubusercontent.com/72772558/178376152-2ff38aaa-f0e0-4bab-b4a2-17b2266a114d.png)

**Comment by Hopelezz** [comment]
On my phone, but I believe the fix here would be :

```css
.container{
   overflow: scroll;
}
```

I'll try to test and make a PR sometime this weekend

https://github.com/unicorn-utterances/unicorn-utterances/blob/main/src/components/filter-search-bar/filter-listbox/filter-listbox.module.scss

**Comment by Hopelezz** [comment]
Another JS I found

```js

var keys = {};
window.addEventListener("keydown",
    function(e){
        keys[e.keyCode] = true;
        switch(e.keyCode){
            case 37: case 39: case 38:  case 40: // Arrow keys
            case 32: e.preventDefault(); break; // Space
            default: break; // do not block other keys
        }
    },
false);
window.addEventListener('keyup',
    function(e){
        keys[e.keyCode] = false;
    },
false);

```

**Comment by crutchcorn** [comment]
@Hopelezz admittedly we do have a setup for scrolling up and down using keyboard. The issue is that we need to figure out how to scroll the UI of the filter list when the keyboard focused element goes off the page.

This is probably as simple as:

```
el.focus();
```

When we tab a keyboard event

**Comment by Hopelezz** [comment]
Looks like you already have the el.focus()

```js
/**
   * Effects
   */
  useEffect(() => {
    // When user escapes using "Esc" key, refocus on btn
    if (!expanded && usedKeyboardLast && buttonNode) {
      buttonNode.focus();
    }
  }, [expanded, usedKeyboardLast, buttonNode]);
```

**Comment by crutchcorn** [comment]
This is no longer an issue as we've temporarily removed the filter list in favor of an upcoming new search page
