### ISSUE TITLE
Need for a Search by author

### ISSUE THREAD

**Issue by kaleem68** [unicorn-utterances/unicorn-utterances#399]
There should be a search by author in the search field.
https://unicorn-utterances.com/

## Solution
- Search option should filter articles by the author's name.
<img width="1406" alt="Screenshot 2022-07-22 at 12 11 44 AM" src="https://user-images.githubusercontent.com/13909729/180296998-46705c84-87c4-45b2-9f78-d3895dc6c6f9.png">

**Comment by crutchcorn** [comment]
Work on this exact problem is being tackled by a brand new search page currently being designed by @PrattiDev

**Comment by crutchcorn** [comment]
This is being closed in the UWU redesign by #601
