### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#4]
In the `src/assets/icons` directory, we have a `dark` and `light` icons that were designed for the site. This feature was cut due to time, but having in toggle in the top right of the header (#3) would make for a better reading experience for users that prefer a dark mode

Because we're using CSS variables, this should be relatively straightforward

**Comment by crutchcorn** [comment]
Attaching designs from the one-and-only amazing @tommyemo 

![about](https://user-images.githubusercontent.com/9100169/61683264-caa92f00-acc9-11e9-8b36-0781f379f05f.png)
![author – searched – expands-1](https://user-images.githubusercontent.com/9100169/61683265-caa92f00-acc9-11e9-8791-dcb54c65083e.png)
![author – searched – expands](https://user-images.githubusercontent.com/9100169/61683266-caa92f00-acc9-11e9-9a01-7ad7b1682d83.png)
![author](https://user-images.githubusercontent.com/9100169/61683267-cb41c580-acc9-11e9-85ec-88e47ac6ed3a.png)
![blog detail view – bottom](https://user-images.githubusercontent.com/9100169/61683268-cb41c580-acc9-11e9-8d4a-3d419fca3aed.png)
![blog detail view – overflow](https://user-images.githubusercontent.com/9100169/61683269-cb41c580-acc9-11e9-9773-1548b6e03070.png)
![blog detail view-3](https://user-images.githubusercontent.com/9100169/61683270-cb41c580-acc9-11e9-87ca-560baf6c593e.png)
![landing – _edited for length_](https://user-images.githubusercontent.com/9100169/61683271-cb41c580-acc9-11e9-8ea6-f83b86f9f297.png)
![landing – scrolled](https://user-images.githubusercontent.com/9100169/61683272-cbda5c00-acc9-11e9-883a-b87bbe34f4a1.png)
![landing – searched + filtered](https://user-images.githubusercontent.com/9100169/61683273-cbda5c00-acc9-11e9-9077-f1f6b7739d8c.png)

**Comment by tommyemo** [comment]
💜✨💥

**Comment by adueppen** [comment]
Something that may require changing with a dark mode is the meta theme-color property. At the moment, it's #127db3, the background color of the logo. This has decent contrast but would look a bit odd in a dark mode.

**Comment by crutchcorn** [comment]
I think that this is a good idea to change that @adueppen, but probably not something we want to address in the initial version. Let's go ahead and make sure that we can change the CSS variables in an initial feature push before worrying about modifying our manifest.

**Comment by adueppen** [comment]
@tommyemo do you have the vector of the little moon icon thing? There are existing dark/light icons but there's something I'd kind of like to try with the moon icon.

**Comment by crutchcorn** [comment]
He does and I have the SVGs for it. Message me on Discord

**Comment by adueppen** [comment]
Connected to #24: switching to dark mode causes disqus comments UI to have poor contrast until the page is reloaded.

**Comment by tommyemo** [comment]
> @tommyemo do you have the vector of the little moon icon thing? There are existing dark/light icons but there's something I'd kind of like to try with the moon icon.

i'd love to see your version if you've got one!

**Comment by adueppen** [comment]
@tommyemo I haven't actually done anything with it yet, but I'll work on it at some point soon.
