### ISSUE TITLE
Unicorn Utterances Sponsorship

### ISSUE THREAD

**Issue by kaleem68** [unicorn-utterances/unicorn-utterances#406]
### Unicorn Utterances sponsership 

- As Unicorn Utterances welcomes the sponsors, there should be a button in the `about` with a welcome sponsorship message i.e button with 'Sponsor us', which goes toward a link to fill the sponsorship form.
### Section
https://unicorn-utterances.com/about
<img width="961" alt="Screenshot 2022-07-27 at 11 35 12 PM" src="https://user-images.githubusercontent.com/13909729/181347021-bc615e27-50b9-4fbc-be15-7760d3ae66c1.png">

**Comment by crutchcorn** [comment]
@fennifith @kaleem68 I know we discussed this more in VC, but do you recall what term we were thinking of replacing "sponsors" with?

Was it "Partners" or "Affiliates" or "Friends" or something else?

**Comment by kaleem68** [comment]
We all were in the view that the word "sponsors" should be replaced with "Partners".
