### ISSUE TITLE
Astro Disclosure

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#455]
Hi all. Just for the sake of transparency and to align with our statement of ethics, I figured I'd disclose my relationship to [Astro](https://astro.build/).

At the time of writing, I am doing some consulting for Astro to write documentation pertaining to migrating sites from a given framework to Astro. For example, I am currently writing guides for migrating from Gatsby to Astro and Next.js to Astro, with others planned in the future.

-----

> Why am you disclosing this?

Well, starting in July 2022, the Unicorn Utterances development team migrated from Next.js to Astro ourselves. We merged PR #386 to complete this migration in December 2022. I was the primary decision maker in choosing Astro as opposed to other SSG tools in the space (such as Jekyll or Eleventy).

This decision was made following a long research spike with @fennifith and a few other Discord members in our `#meta` channel. We were particularly looking for a tool that enables us to ship as little or no JavaScript to the site and found that Astro was our favorite tool in terms of componentization and data loading.

Why migrate to Astro at all? Ultimately, this migration to Astro was driven by a desire to improve our Lighthouse scores in an effort to improve SEO with the upcoming release of my Unicorn Utterances published book ["The Framework Field Guide"](https://framework.guide). Our migration almost doubled our lighthouse scores across every page, and in conversations I've had, @fennifith and I are both fairly happy with the migration as a whole.
 
-----

> Was the decision to migrate to Astro contingent on a future consulting contract?

Absolutely not. While I was in conversations with Astro core members (namely @jutanium and @aFuzzyBear) who helped us research and do initial explorations, I didn't even entertain the idea that I would be given this opportunity.

It wasn't until **after** the migration of Unicorn Utterances to Astro that Astro's CEO, @FredKSchott, suggested the idea, as they were looking for someone who had experience with such migrations to do documentation.

-----

> Does Astro have any control over the technology stack or any other aspect of Unicorn Utterances?

**Astro has zero control over any aspect of Unicorn Utterances**. While we're pleased with our decision to use Astro for the site, should another tool down the line serve our needs better, and it makes sense to migrate to it, we will. Further, they have no control over what any of the community members say or do. If someone doesn't like Astro for any reason, they have full right to vocalize this opinion, so long as it follows our general Code of Conduct.

----

Please feel free to raise any concerns or comments regarding this relationship.

**Comment by crutchcorn** [comment]
Closing to avoid cluttering open issues.

This does not mean the conversation is closed off to others or unrelated. Please feel free to comment anything related

**Comment by ThorondorManwe** [comment]
**Spanish Translation**

# Reconocimiento: Astro
____________

Hola a todos. Solo por el bien de la transparencia y para mantenernos alineados con nuestra declaración de ética, pensé en revelar mi relación hacia [Astro](https://astro.build/).

Al momento de escribir esto, estoy haciendo consultoría para Astro para escribir documentación relacionada con la migración de sitios de un framework determinado a Astro. Por ejemplo, actualmente estoy escribiendo guías para migrar de Gatsby a Astro y de Next.js a Astro, junto con otras que tengo planeadas para el futuro.

---

> ¿Por qué te revelo esto?

Bien, a partir de julio del 2022, en el equipo de desarrollo de Unicorn Utterances migramos de Next.js a Astro. Combinamos el PR [#386](https://github.com/playfulprogramming/playfulprogramming/pull/386) para terminar esta migración en diciembre del 2022. Yo fui el principal responsable de tomar la decisión de elegir Astro en lugar de otras herramientas SSG (como Jekyll or Eleventy).

Esta decisión se tomó después de una larga investigación con [@fennifith](https://github.com/fennifith) y algunos otros miembros de Discord en nuestro canal `#meta`. Buscábamos una herramienta que nos permitiera enviar la menor cantidad de JavaScript posible al sitio y descubrimos que Astro era nuestra herramienta favorita en términos de componentización y carga de datos.

¿Por qué migrar a Astro? Al final, esta migración a Astro fue impulsada por el deseo de mejorar nuestras puntuaciones de Lighthouse en un esfuerzo por mejorar el SEO con el próximo lanzamiento de mi libro publicado en Unicorn Utterances ["The Framework Field Guide"](https://playfulprogramming.com/collections/framework-field-guide). Nuestra migración casi duplicó nuestras puntuaciones de Lighthouse en todas las páginas y, en las conversaciones que he tenido, [@fennifith](https://github.com/fennifith) y yo estamos bastante contentos con la migración en general.

---
> ¿La decisión de migrar a Astro estuvo condicionada a un futuro contrato de consultoría?

En lo absoluto. Mientras conversaba con miembros principales de  Astro (dígase [@Jutanium](https://github.com/Jutanium) y [@aFuzzyBear](https://github.com/aFuzzyBear)) quienes nos ayudaron a investigar y realizar exploraciones iniciales, ni siquiera se me ocurrió la idea de que me darían la oportunidad.

No fue sino hasta **después** de la migración de Unicorn Utterances a Astro que el CEO de Astro, [@FredKSchott](https://github.com/FredKSchott), me sugirió la idea de que estaban buscando a alguien que tuviera experiencia con este tipo de migraciones para hacer la documentación.

---

> ¿Astro tiene algún tipo de control sobre el *stack* de tecnologías o cualquier otro aspecto de Unicorn Utterances?

**Astro no tiene ningún tipo de control sobre cualquier aspecto de Unicorn Utterances**. Aunque estamos contentos con nuestra decisión de usar Astro para el sitio, en el caso de que en el futuro surja otra herramienta que sirva mejor a nuestras necesidades y tenga sentido migrar a ésta, haremos el cambio. Si, por algún motivo, a alguien no le gusta Astro, está en su derecho de expresar su opinión, siempre y cuando cumpla con nuestro Código de Conducta.

---

No dudes en plantear cualquier inquietud o comentario respecto de esta relación.
