### ISSUE TITLE
Support word count on .mdx posts

### ISSUE THREAD

**Issue by fennifith** [unicorn-utterances/unicorn-utterances#498]
Currently, [rehype-word-count.ts](https://github.com/unicorn-utterances/unicorn-utterances/blob/main/src/utils/markdown/rehype-word-count.ts) does not process mdx files when determining a post's word count.

This should be changed to better support mdx content, with the goal of matching regular markdown posts as closely as possible in terms of what counts as a "word" (excluding any actual mdx components).

**Comment by crutchcorn** [comment]
This should now be fixed, as we've removed the `rehype-word-count` plugin
