### ISSUE TITLE
IFrame embeds don't propagate `allowfullscreen`

### ISSUE THREAD

**Issue by fennifith** [unicorn-utterances/unicorn-utterances#528]
The current `click-to-run-iframe` implementation seems to remove most additional properties specified in markdown (or by embed transforms) when creating the iframe element on the client. This includes attributes like `allowfullscreen` (in e.g. video embeds) and `scrolling="no"`, although I'm sure there are others we might also want: <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attributes>

These should ideally be passed through in a `data-` property for the client js to create them.

**Comment by crutchcorn** [comment]
This is fixed now: https://github.com/unicorn-utterances/unicorn-utterances/pull/701
