### ISSUE TITLE
Nested content folder structure (suggestion)

### ISSUE THREAD

**Issue by fennifith** [unicorn-utterances/unicorn-utterances#532]
The `content/posts` directory is quite large and potentially difficult to navigate at the moment - it would be a potentially useful feature for authors or collections to have their own subfolder to store particular sets of posts inside

For example...
```
content/
└── {author}/
    ├── index.md
    ├── profile.png
    ├── {post}/
    │   └── index.md
    └── {collection}/
        ├── index.md
        └── {post}/
            └── index.md
```

In this case, `{author}/index.md` would contain the current author data in the frontmatter. Posts and collections would live within a certain author folder (which does not prevent collaborative posts - although they would need to choose a primary author in the source tree).

**Comment by crutchcorn** [comment]
I think I'd rather a variation on this that's easier for us to parse programatically:

```
content/
└── {author}/
    ├── index.md
    ├── profile.png
    ├── posts/{post}/
    │   └── index.md
    └── collections/{collection}/
        ├── index.md
        └── posts/{post}/
            └── index.md
```
