### ISSUE TITLE
Allow different timestamp formats, or remove entirely

### ISSUE THREAD

**Issue by fennifith** [unicorn-utterances/unicorn-utterances#533]
The current "created" and "updated" post metadata properties require raw timestamp formatting that often isn't used correctly (i.e. we ignore the exact time and only change the date), and can be an easy source of typos.

This could be changed to allow omitting the full timestamp (e.g. by only providing the `MM-DD-YYYY` format) or potentially removed entirely -

TBD: I recall some earlier discussion about possibly deriving the created/updated timestamps from git without any need for author input. How feasible is this - could it be added to our rehype plugins?

**Comment by crutchcorn** [comment]
I **really** strongly don't want to remove the date field. Relying on Git's internal tracking is fragile and can easily break if a file is renamed and whatnot

Happy to change it to:

```
yyyy/mm/dd
```

But if we allow any other format:

```
mm-dd-yyyy
```

It's easy for us to get confused in:

```
dd-mm-yyyy
```

As cultural differences there arise

**Comment by fennifith** [comment]
Huh, nvm apparently - I just tried `published: '2023-04-11'` in a post and it works as expected. We're using [DayJS](https://day.js.org/docs/en/parse/string) for date parsing, which references [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) - which appears to support a lot of different formats. So I don't think anything is needed to support this.

Closing!
