### ISSUE TITLE
Alphabetize the about us page

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#56]
While entirely unintentional, we've ended up with the about us screen being placed in the same order of folks in the `unicorns.json` file. 

In order to keep things non-biased and equal, I think it'd be a good idea to alphabetize them with a GraphQL sort (so we don't have to force new PRs to worry about this)

**Comment by crutchcorn** [comment]
Copying some convo on this ticket from our Discord:

> Once there are enough people for it to make sense, would it be more comprehensive to organize by role, then list alphabetically within that?

> I think at that point we should sort by official team members and THEN contributors

> I know some OSS projects do by # of commits

> I think # of commits would be reasonable

Paging @adueppen @fennifith @evelynhathaway as we never resolved this one - do we want to sort by commit # long-term? (I still think as a short-term gap sorting by alphabet until further development can be done on #65 (which discusses some design considerations for the technical aspect of tracking commit #s))

**Comment by crutchcorn** [comment]
It's time to do this properly as part of #867, as we're no longer relying on the array of people to dictate the order.

Nowadays, we have our partner program. As such, we're going to sort partners first (one of the perks we're offering, especially since a future redesign of the About Us page will have partners listed separately before other contributors), then by whatever metric we should decide.

I vote that we keep it simple and do alphabetical. Otherwise, we could sort by how many achievements (a new feature since this was last discussed) someone has.

What do we think?

**Comment by chtnnh** [comment]
@crutchcorn I came across unicorn-utterances on LinkedIn via a post on "The Framework Field Guide". Would love to help out!

Since this is a beginner friendly issue and is not critical in the near future, would love to begin here. Let me know if it's okay to send a PR and I'll shoot one across at the earliest possible time I can

**Comment by crutchcorn** [comment]
Hey @chtnnh - this is immensely appreciated, but I have actually done this work in #867

Instead, do you have any interest in this issue?

https://github.com/unicorn-utterances/unicorn-utterances/issues/856

**Comment by chtnnh** [comment]
@crutchcorn would recommend we follow something along the lines of the recommendations of https://stacking.dev to quickly onboard high-intent contributors to the community.

requesting you to start a discord thread on this, as opposed to a github issue. (in my limited experience maintaining open source projects, 1 central store for related information always helps)
