### ISSUE TITLE
Ctrl+Click on a post card does not have consistent behavior

### ISSUE THREAD

**Issue by fennifith** [unicorn-utterances/unicorn-utterances#573]
Currently, the `<a>` title within a post card can be ctrl+clicked to open it in a new tab. However, this also activates the `onclick` and navigates the current page to the clicked post.

Ctrl+clicking elsewhere on the post (outside of the `<a>` tag) only activates the `onclick`, which navigates the current page and does not open a new tab.

The `<a>` element _can_ be right clicked to use "open in new tab" from the context menu, which works as expected. However, right clicking on the post card outside of the `<a>` does not provide these options.

Open to discussion on how these cases should be handled, since the `onclick` event doesn't normally define "open in new tab" behavior to begin with. However, the `<a>` used for post titles *can* still open links in a new tab, so it might be good to prevent the `onclick` from running if the click originated within the `<a>` element.

**Comment by crutchcorn** [comment]
Potentially related:

https://twitter.com/devongovett/status/1672307153699471360?s=20
