### ISSUE TITLE
Fix linting warnings present when running `npm run develop`

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#62]
Due to an upgrade of React (alongside some malpractices of hooks applied by myself), we've ended up with various warnings regarding how hooks (and other areas) are being used. It would be great if we could get these warnings to silence by fixing those problem areas

**Comment by MDutro** [comment]
Rookie question - where are these warnings displayed?

**Comment by crutchcorn** [comment]
They're displaying whilst running `npm run develop`

**Comment by MDutro** [comment]
I'm sorry. Should I see the warnings in the terminal? Or in the console when running the local host?

**Comment by crutchcorn** [comment]
It's okay. I MIGHT have resolved the issues already, but if they're still there, it should show in the terminal once the project is built

**Comment by MDutro** [comment]
It may need more testing but I'm not seeing any errors or warnings in my terminal after 'npm run develop' completes.

So... good work!
