### ISSUE TITLE
[UwU] Each checkbox should not have its own focus

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#644]
Each of these checkboxes currently have a focus ability, instead we should have a key handler to navigate up/down using arrow keys instead.

<img width="167" alt="image" src="https://github.com/unicorn-utterances/unicorn-utterances/assets/9100169/fb6f6ff6-3077-40e1-b674-1d09a3768bd8">

**Comment by GrahamTheDevRel** [comment]
My initial thought is to use something like the Gov UK multi-select pattern: https://accessibility.blog.gov.uk/2019/04/08/accessibility-lessons-dealing-with-a-large-amount-of-form-inputs/

**Comment by crutchcorn** [comment]
Per @GrahamTheDevRel's article and the Gov.UK website, I think we're going to simply fix #646 and #643 - leaving the tab-to-focus checkboxes
