### ISSUE TITLE
Enable auto-tagging editors to a post

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#65]
Just as we're able to auto-assign roles for an author based on frontmatter tagging, I would also like to be able to auto-assign the role of "editor" on folks who are not the author but make commits for a post.

The way I would like to do this is by building out a `gatsby` plugin that provides `git` data from the repo itself into the GraphQL. This would also add fields for `File` and `MarkdownRemark` nodes. Due to the required research phase/etc I am going to assign myself to this

Some questions that need to be solved for:

- [ ] If we do want to use direct local git repo info, what library do we want to use to get the git info on a file?
- [ ] How would we track the user's git info? (a commit contains an email that might not be associated with a user)

We might be able to solve some of this just by using GH API v4:
```
query {
  repository(owner: "unicorn-utterances", name: "unicorn-utterances") {
    ref(qualifiedName: "integration") {
      target {
        ... on Commit {
          history {
            pageInfo {
              hasNextPage
              endCursor
            }
            edges {
              node {
                author {
                  name
                }
              }
            }
          }
        }
      }
    }
  }
}
```

https://developer.github.com/v4/explorer/

But then the questions are:

- [ ] How do we handle the GH API auth call?
- [ ] When do we query that data?
   - [ ] And do we mock it util then?
- [ ] Do we really want to limit ourselves as an org to be reliant upon GH's APIs? 
    - [ ] How does this potentially align/affect our goal to have self-rolled auth long-term?

At this stage, I think there's a lot of questions to be had, but it's good to get them down for now

**Comment by fennifith** [comment]
Closing this as out of date - we've since gone down the route of making things explicitly specified in frontmatter, rather than performing git/GH queries for post metadata.

Similar questions arose with whether we should automate the "created / updated" timestamps in this manner, IIRC. This means that small or unrelated edits/refactors can be made without affecting the post data if needed, and it doesn't tie the site to a particular git repo/host.
