### ISSUE TITLE
[UwU] (Search page) Selecting text on a search filter causes unreliable click behavior

### ISSUE THREAD

**Issue by fennifith** [unicorn-utterances/unicorn-utterances#652]
- Navigate to [`/search`](https://unicorn-utterances-git-uwu-oceanbit.vercel.app/search)
- Enter any search query
- Highlight either the label text or count next to a filter checkbox
- Click on the filter checkbox

Expected: the filter checkbox should toggle its state
Actual behavior: the checkbox seems to activate its "focus" state on mousedown, but returns to the opposite state on mouseup.

https://github.com/unicorn-utterances/unicorn-utterances/assets/13000407/40e38e2e-90dd-4a40-b04b-30966f02347b

**Comment by crutchcorn** [comment]
I sincerely believe this might just be browser behavior. I dunno how to fix this otherwise

**Comment by fennifith** [comment]
I did some more poking at this and found that the issue only occurs when either:
- Any text in the filter label is selected, and the checkbox icon is clicked on
- OR the text selection encompasses the checkbox icon itself

...and then I found that it was possible to select nodes inside the checkbox icon itself, even though there is no visual indication when that occurs (or any content to select - except maybe the svgs?). Adding `user-select: none;` to the checkbox icon prevents this from occurring.
