### ISSUE TITLE
[UwU] (Search page) Error state text is sometimes overlapped by the randomized logo icons

### ISSUE THREAD

**Issue by fennifith** [unicorn-utterances/unicorn-utterances#654]
![2023-08-22-123428_1075x602_scrot](https://github.com/unicorn-utterances/unicorn-utterances/assets/13000407/0720641a-ad89-463f-9e87-4912b36bbd82)

This could be fixed by changing the z-index of the content and applying the same styling as the homepage on [`.bannerTextShadow`](https://github.com/unicorn-utterances/unicorn-utterances/blob/uwu/src/components/hero/hero.module.scss#L37) to ensure contrast.

**Comment by crutchcorn** [comment]
Reopening as I hadn't realized the mentioned commit was reverted.

I think we should solve this by adding a text outline the same color as the background and changing the sticker's z-index, as we cannot reasonably predict where text will be for all font sizes
