### ISSUE TITLE
[UwU] (Search page) Search results are always sorted by date

### ISSUE THREAD

**Issue by fennifith** [unicorn-utterances/unicorn-utterances#661]
![2023-08-23-001757_417x153_scrot](https://github.com/unicorn-utterances/unicorn-utterances/assets/13000407/b6552453-0641-4e04-aaf5-9340f8fe0d5a)

Currently, the search page always sorts all articles returned from the search query by their date, either ordered newest or oldest first. This invalidates the result "scoring" that FuseJS does to return the most relevant results first.

For example, searching for "test" should ideally rank articles directly containing the word "test" in their title/description at the top, followed by articles with less direct references, as returned by FuseJS:
![2023-08-23-001509_544x79_scrot](https://github.com/unicorn-utterances/unicorn-utterances/assets/13000407/bcd4fb77-7e14-45e0-939c-5ed49bbfb5cc)

However, when sorted by date, these results are not on the first page... or the second... or the third. This issue is more noticeable with less specific search queries (like this one) that return a lot of matches.

Ideally, the search page should provide the results unmodified (sorted by score) by default, allowing the newest/oldest sorting to be toggled off or by providing "relevant" as a third option.

**Comment by crutchcorn** [comment]
Let's solve this by:

- Not having a default
- Clicking the current selected sort  to unselect it
- Add a blank option in the dropdown
