### ISSUE TITLE
Add table of contents for blog posts

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#7]
It would be great to have a table of contents off to the side on desktop

![blog detail view – bottom](https://user-images.githubusercontent.com/9100169/61683380-24a9f480-acca-11e9-844b-a377912cb582.png)

Design from @tommyemo 

A question that I have is what we'd have for mobile. I think a dropdown in the header area might be nice - but I'm overall unsure where this would go for now. Initial version should likely be desktop only for now.

Should use [the gatsby-transformer-remarked plugin's `tableOfContents`](https://www.gatsbyjs.org/packages/gatsby-transformer-remark/#getting-table-of-contents)

**Comment by tommyemo** [comment]
I think for mobile a bottom bar of sorts may work ... I'll play with it

**Comment by crutchcorn** [comment]
Work is in progress on the `headings-with-id-plugin` branch. Turns out it's more tricky than it'd seemed to've been

**Comment by crutchcorn** [comment]
We're now blocked by this:

https://github.com/gatsbyjs/gatsby/issues/22287
