### ISSUE TITLE
Index localized pages as adjacent links in the HTML header / sitemap

### ISSUE THREAD

**Issue by fennifith** [unicorn-utterances/unicorn-utterances#716]
According to google's docs, there are a few things the site should be doing to index its translated pages: https://developers.google.com/search/docs/specialty/international/localized-versions#all-method-guidelines

- While we provide HTML `<link rel="alternate">` header tags for translations, it excludes the link entry for the current page, whereas the docs specify:
  > one link for each page variant **including itself**.

  > If two pages don't both point to each other, the tags will be ignored. This is so that someone on another site can't arbitrarily create a tag naming itself as an alternative version of one of your pages.

  I think this means that localized pages are not currently being indexed correctly. (this can be tested on the [hreflang tool](https://technicalseo.com/tools/hreflang/) linked in their docs)

- Additionally, the language attribute is declared as `href-lang=""`, whereas it should be [`hreflang=""`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#hreflang) (with no hyphen - I'm not sure if page crawlers can still resolve the attribute, but it should probably be fixed regardless)

- **TODO:** it is unclear if `hreflang="x-default"` should be provided alongside an additional `hreflang="en"` entry, since those would be the same link in our case.

  Looking at other sites:
    - MDN does not specify an `hreflang="x-default"` and only provides an `hreflang="en"`
    - Google's docs site provides both `hreflang="x-default"` and `hreflang="en"`, which have the same URL

  So it seems like UU could do either.
  
- Additional `<xhtml:link rel="alternate">` links can be added to the sitemap for these pages.

  This may be as simple as providing the [i18n](https://docs.astro.build/en/guides/integrations-guide/sitemap/#i18n) config to the Astro sitemap integration. However, the docs seem to imply that an "alternate" link entry is created for every locale defined in this config; we need to confirm that this doesn't create entries for pages that don't exist.

  Of note: Astro's sitemap integration assumes that the lang code [is always in the first segment of the URL](https://github.com/withastro/astro/blob/main/packages/integrations/sitemap/src/generate-sitemap.ts#L35); any other placement might fail - likewise if a lang code is not provided in the config.

**Comment by crutchcorn** [comment]
<img width="631" alt="image" src="https://github.com/unicorn-utterances/unicorn-utterances/assets/9100169/d2229c86-385b-4c43-9a3a-65666889f72b">

Confirmed that the `i18n` config to sitemap works as we'd expected
