### ISSUE TITLE
Accessibility: Decorative button icons should be hidden from the accessibility tree

### ISSUE THREAD

**Issue by evelynhathaway** [unicorn-utterances/unicorn-utterances#720]
On the uwu branch (PR https://github.com/unicorn-utterances/unicorn-utterances/pull/497), the semantics of "Discord" or clicking a link to learn more have been conveyed by the adjacent link text, and the SVG does not have a `<title>` or `aria-label` (i.e. not a critical icon). Therefore it should be hidden using `aria-hidden`.

![Screenshot of div.buttonIcon in the Join our Discord button link](https://github.com/unicorn-utterances/unicorn-utterances/assets/38994283/824cb21e-6707-4d9c-afc1-4a16c75d5583)

![Screenshot of div.buttonIcon in the Learn more button link](https://github.com/unicorn-utterances/unicorn-utterances/assets/38994283/1588a921-a2a5-4212-ae50-05d2cbbf6e30)

**Comment by crutchcorn** [comment]
This should not be an issue on any button anymore, as I applied the fixes to every icon button
