### ISSUE TITLE
[UwU] Heading anchor links can overlap other UI elements

### ISSUE THREAD

**Issue by fennifith** [unicorn-utterances/unicorn-utterances#733]
![2023-09-28-191103_790x389_scrot](https://github.com/unicorn-utterances/unicorn-utterances/assets/13000407/5b346029-12ec-4803-824b-bf5a7ffda11a)

These icons should likely be moved to not overlap the table of contents.

They could also have a background/border to set them apart from other content (as they could also appear in lists and tab containers, which could also shift them around the page enough to cause overlap).

**Comment by crutchcorn** [comment]
This likely needs improved designs from @PrattiDev
