### ISSUE TITLE
[UwU] Improve A11Y label for search filter dropdown

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#752]
<img width="366" alt="image" src="https://github.com/unicorn-utterances/unicorn-utterances/assets/9100169/9168b729-7e00-4a75-9ba5-df524b813e07">

**Comment by crutchcorn** [comment]
<img width="700" alt="image" src="https://github.com/unicorn-utterances/unicorn-utterances/assets/9100169/311a7d20-f592-4ab0-ac2a-fac8d2bee1fc">

Same with `Clear` button. Should probably be `clear selected tags` or something instead

**Comment by evelynhathaway** [comment]
How about the a fieldset or multiselect listbox instead of a series of plain checkboxes too? I think it could be named `Tag (x selected)` and be a disclosure toggle, as it is now, but also include aria indicating its relation to the listbox, and the listbox could have improved focus controls as tabbing through all of the checkboxes is a pain (I love the skip link to the search bar)

**Comment by crutchcorn** [comment]
@evelynhathaway I think that's a great idea. I was originally opposed, as we were trying to follow [how the UK Gov website does search filters similar to this](https://www.gov.uk/search/all?keywords=Test&order=relevance), but it turns out they do what you're suggesting:

<img width="816" alt="image" src="https://github.com/unicorn-utterances/unicorn-utterances/assets/9100169/1523e304-7738-428c-b73d-297e922ce870">

**Comment by crutchcorn** [comment]
Also, a feature worth highlighting that we implemented related to "tabbing the  checkboxes is a pain" - when the area is collapsed, we remove them from the tab order, just like the UK's website. This was suggested by @GrahamTheDev as the method we should generally follow per this article:

https://accessibility.blog.gov.uk/2019/04/08/accessibility-lessons-dealing-with-a-large-amount-of-form-inputs/

**Comment by GrahamTheDevRel** [comment]
Hey, I have a mess with handles, this is my active handle if you wanna tag me in the future: @GrahamTheDevRel
