### ISSUE TITLE
[UwU] Mark expanded post image as decorational

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#755]
Required to set this image to `alt=""` or `aria-hidden` to avoid reading out, since it's pretty presentational and doesn't add much value:

![telegram-cloud-photo-size-1-5535443289940011030-y](https://github.com/unicorn-utterances/unicorn-utterances/assets/9100169/bdff9690-f00e-4a9a-b590-726047c8d245)

@evelynhathaway seems to agree with this take

**Comment by evelynhathaway** [comment]
Yeah they are never custom or unique images, right? They are always the post tag represented as a screenshot of code that cannot be read with low contrast for visual variation and decoration

**Comment by crutchcorn** [comment]
Right right @evelynhathaway - autogenerated images that don't provide value outside of looking nice visually
