### ISSUE TITLE
[UwU] Remove role image alt text

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#758]
<img width="489" alt="image" src="https://github.com/unicorn-utterances/unicorn-utterances/assets/9100169/69516a6a-c562-4741-a4e0-123ec80fe370">

This is presentational, let's remove it. @evelynhathaway agrees

**Comment by evelynhathaway** [comment]
I think this issue title should say `unicorn roles` instead of `post` or something :)

**Comment by crutchcorn** [comment]
Whoops! I must've typo-d. I was making a lot of issues at the time. Thanks!
