### ISSUE TITLE
[UwU] Improve enhanced color contrast ratio thresholds for darkMode

### ISSUE THREAD

**Issue by dreyfus92** [unicorn-utterances/unicorn-utterances#766]
I think that you guys can improve the contrast ratio of this p tags that are located at the index.

![image](https://github.com/unicorn-utterances/unicorn-utterances/assets/85648028/f5d22d37-fc63-4566-81c7-650a4c12379a)

![image](https://github.com/unicorn-utterances/unicorn-utterances/assets/85648028/2d694f1c-fb25-412a-b1e3-642677c60763)

![image](https://github.com/unicorn-utterances/unicorn-utterances/assets/85648028/e4e721f5-6c20-4712-a84f-c79daa282859)

Picking one of the suggested options:

![image](https://github.com/unicorn-utterances/unicorn-utterances/assets/85648028/13bda24b-ff58-4e93-8d68-dd495d7571f3)

**Comment by crutchcorn** [comment]
CC @PrattiDev

**Comment by PrattiDev** [comment]
Changes for this issue

- [ ] `$neutral95_64` to `$neutral95_72` (Change the `0.64` alpha value to `0.72`)
- [ ] `$neutral10_64` to `$neutral10_72` (Change the `0.64` alpha value to `0.72`)
- [ ] Remove  `--foreground.emphasis-none`
- [ ] Remove `--foreground.emphasis-low`
- [ ] Remove `$neutral95_32` and `$neutral95_12`
- [ ] Remove `$neutral10_32` and `$neutral10_12`

@crutchcorn
