### ISSUE TITLE
Hide components that require JS in SSR

### ISSUE THREAD

**Issue by adueppen** [unicorn-utterances/unicorn-utterances#77]
Currently, components such as the theme switch button, filter/search, etc that require JS to function still appear on the SSR'd version of the website. Ideally those components should only be rendered when it can be confirmed that JS is available on the client.

**Comment by crutchcorn** [comment]
This should be done using a `useContext` and `useEffect` hook combo

**Comment by crutchcorn** [comment]
One of my concerns with this is that it will inevitably cause issues with [Content Layout Shift (CLS)](https://web.dev/cls/), which is something of a nightmare from a UX perspective.

As such, I'm extremely hesitant on implementing this behavior.

@adueppen @fennifith what do you think?

**Comment by crutchcorn** [comment]
Closing, as this will cause immense CLS issues
