### ISSUE TITLE
[UwU] Improve contrast ratio in `/about` for locale picker

### ISSUE THREAD

**Issue by dreyfus92** [unicorn-utterances/unicorn-utterances#775]
The lang-picker can be as well improved.

![image](https://github.com/unicorn-utterances/unicorn-utterances/assets/85648028/b7e7ca26-bf8c-4a3a-8ba6-fd50bf242831)

![image](https://github.com/unicorn-utterances/unicorn-utterances/assets/85648028/c1954b93-660a-46e2-910e-692be9f077ab)

![image](https://github.com/unicorn-utterances/unicorn-utterances/assets/85648028/ec7a7b66-195f-4fa0-ad80-55032b1eaa57)

By picking one of the options: 

![image](https://github.com/unicorn-utterances/unicorn-utterances/assets/85648028/3c6e8fba-ecfb-4a80-9004-f4698a8d9664)

**Comment by crutchcorn** [comment]
CC @PrattiDev

**Comment by crutchcorn** [comment]
Marking this as "won't fix", as:

- Meets AA contrast giudelines
- Is an intentionally visually disabled element
- WCAG 2.2 guidelines no longer require contrast guidelines on disabled elements

However, we did add an `aria-current="page"` to help improve non-sighted users that we missed before
