### ISSUE TITLE
[UwU] Ensure that the page, or at least one of its frames contains a level-one heading in `/about`

### ISSUE THREAD

**Issue by dreyfus92** [unicorn-utterances/unicorn-utterances#776]
One of the best practices is to ensure that the page, or at least one of its frames contains a level-one heading `<h1>`

Here are a couple of resources that talk about it:
- https://rocketvalidator.com/accessibility-validation/axe/4.8/page-has-heading-one
- https://www.a11yproject.com/checklist/#use-only-one-h1-element-per-page-or-view

**Comment by crutchcorn** [comment]
Oh! We must've just missed this. Will likely make it an invisible H1, thank you
