### ISSUE TITLE
[UwU] Aria hidden elements must not be focusable or contain focusable elements.

### ISSUE THREAD

**Issue by dreyfus92** [unicorn-utterances/unicorn-utterances#784]
I'm not 100% sure on this one, it's noteworthy that elements with aria-hidden set to true typically should not be made focusable, nor should they contain focusable elements.

![image](https://github.com/unicorn-utterances/unicorn-utterances/assets/85648028/ab8e7609-f852-448e-9e93-b72255e45f8d)

Here I share a couple of resources that talk about it:
- https://dequeuniversity.com/rules/axe/4.3/aria-hidden-focus
- https://rocketvalidator.com/accessibility-validation/axe/4.8/aria-hidden-focus

This div is located here: https://unicorn-utterances-git-uwu-oceanbit.vercel.app/search?searchQuery=*&display=collections&filterTags=

**Comment by crutchcorn** [comment]
This should be fixed in #790
