### ISSUE TITLE
Add support for various licenses to be added to individual posts 

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#8]
- [ ] Define a structure for LICENCE.md to be placed in a file (or a frontmatter field?)
- [ ] If not using frontmater field, add the LICENCE.md to the GraphQL calls for Unicorn Utterances
- Provide a default licence? (@fennifith what do you think? @evelynhathaway do you know of any reason legally we couldn't/shouldn't do this? I don't know if we should, seeing as one could accidentally commit a post and that way we can CI to force a check for a LICENCE.md file and remove legal ambiguity) [NOT DOING, SEE BELOW](https://github.com/unicorn-utterances/unicorn-utterances/issues/8#issuecomment-519569689)
- [ ] Mention the licence layout in README.md
- [ ] Include an image of that licence in the bottom or have a sidebar with info @tommyemo would love some thoughts on a design for this. I don't know what would look better or where things would go

**Comment by fennifith** [comment]
I don't think a default license should be provided, tbh. We can have a "primary license" or suggest a few of them in the README and have [pull request templates](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository) for contributors to choose from, but IMO having default licenses would make it too easy to publish something "by mistake", as you said.

**Comment by crutchcorn** [comment]
I like having a primary licence, suggest them (and probably point to something like https://tldrlegal.com/), and provide a PR template would all be solid options that I like significantly more than having a default license

**Comment by crutchcorn** [comment]
We have initial work on this completed. I have further questions about what we want to do in the future but it seems out-of-scope. 

Closing this in favor of: #35
