### ISSUE TITLE
Full results of search do not match

### ISSUE THREAD

**Issue by adueppen** [unicorn-utterances/unicorn-utterances#82]
Searching for "freenod", "free", etc comes up with the freenode IRC posts, but searching for "freenode" comes up with no results. Similarly, "introduct" comes up with 2 articles with "introduction" in their names, but as soon as any of the last 3 letters are added it finds nothing. This will need some more testing to figure out the root cause.

**Comment by crutchcorn** [comment]
This also breaks filtering - where we're using `lunr` to use the filter
