### ISSUE TITLE
[UwU] Large search input caret is not shown initially

### ISSUE THREAD

**Issue by PrattiDev** [unicorn-utterances/unicorn-utterances#822]
![image](https://github.com/unicorn-utterances/unicorn-utterances/assets/17130024/7b51ed88-e641-489a-83bc-f2517e0769a4)

Switching to another tab and back fixes the issue.

**Comment by crutchcorn** [comment]
I firmly believe this is a Chrome bug, but cannot find an easy trace of why. This doesn't occur in Firefox, but does occur in Edge

**Comment by crutchcorn** [comment]
Relevant code is found here:

https://github.com/unicorn-utterances/unicorn-utterances/tree/uwu/src/components/input

@fennifith thinks it might be related to the following:

https://github.com/unicorn-utterances/unicorn-utterances/blob/uwu/src/components/input/input.module.scss#L70
