### ISSUE TITLE
Search page checkboxes don't toggle when checkbox label is selected

### ISSUE THREAD

**Issue by rjt-rockx** [unicorn-utterances/unicorn-utterances#843]
Ideally it should discard further interactions till the state has been updated or debounce till the last interaction.
https://github.com/unicorn-utterances/unicorn-utterances/assets/10488070/34c0d66f-f76a-4226-9956-bcb8263d6093

**Comment by crutchcorn** [comment]
This isn't _really_ a bug, as it's technically the URL state that you're updating, which updates the rest of the state 😅

That said, what debounce level do you think would be appropriate for this?

**Comment by rjt-rockx** [comment]
makes sense, not sure what the ideal level would be but preferably around a second or so, just long enough to ensure that it doesn't get stuck with that behavior

**Comment by fennifith** [comment]
I'm not convinced that this actually causes any kind of loading state - I'd expect `react-query` to have defaults that prevent this from occurring? (not to mention it's already put through a `useDebouncedValue`, assuming that works as expected)

This looks more like #652, where some clicks to the checkbox cause two callback events when there is a text selection, resulting in no change to the search query (and no requests being sent) - and that is what I can reproduce with testing.

The solution in #652 was preventing nodes without a visible selection state - i.e. the svg icon - from being selected. However, afaik this isn't an actual `click` event that you're seeing - it's interpreted as acting on the text selection, and is not sent to the `onClick` handler. I'm not sure of any way to prevent this without preventing any user text selection in the first place.

So - even though it's not the most intuitive - I'm inclined to say this is intended behavior. Selecting text should not change the checkbox value (this is browser-defined behavior) unless we want to turn off text selection entirely.

**Comment by crutchcorn** [comment]
@fennifith I'm not sure that's what @rjt-rockx is saying here.

Instead, I believe @rjt-rockx is saying that "Hey, if I spam-click the filter checkboxes, we end up with a **ton** of URL history items."

This is because **every time** the user changes the filters, we push the updates to the URL. I believe @rjt-rockx is asking us to debounce this URL state updating with a delay of 1s so that the user can spam-click as much as they'd like while being able to still navigate backwards within reason

**Comment by rjt-rockx** [comment]
My bad, I didn't articulate things properly
I wasn't exactly looking into selecting text or URL history items - I clicked multiple times on a tag expecting it to just toggle back and forth on every alternate click like the typical checkbox, but it didn't, instead just not doing anything apparently? I didn't see any indication as to whether it was actually toggling it back and forth, and I had no idea if the page was even responding to my clicks, or if it used the value of the last click to update the filter state

**Comment by MateuszWasik** [comment]
@crutchcorn Hi, I went through this bug again and it looks like it's fixed. I am not able to reproduce this behaviour. There is no delay or "empty" checkbox action. One click one toggle.
 
Below is the video. I was clicking very rapidly :D 

![UU_bug_proof](https://github.com/unicorn-utterances/unicorn-utterances/assets/26119440/5a3bc478-d12c-4ec0-a59b-57eaa10fbee9)

**Comment by crutchcorn** [comment]
Yay! 😊 This is great to hear!

@rjt-rockx let's open a new issue if this fix isn't working as you'd otherwise expect
