### ISSUE TITLE
Word count styling is not consistent between pages

### ISSUE THREAD

**Issue by PrattiDev** [unicorn-utterances/unicorn-utterances#863]
![image](https://github.com/unicorn-utterances/unicorn-utterances/assets/17130024/6d9152e4-b3d9-465c-96c1-6b44c6017a95)
![image](https://github.com/unicorn-utterances/unicorn-utterances/assets/17130024/7ac7ea01-6a15-41fe-b3e4-b9ecc33db7bd)

Ideally we should apply the comma to the card count as well.

**Comment by crutchcorn** [comment]
@fennifith is tackling this
