### ISSUE TITLE
Add steps to make a PR to Tweet out a promo when a post is merged into master

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#89]
Currently, we have a way to tweet from the [official Unicorn Utterances twitter page](https://twitter.com/UnicornUttrncs) via:
https://github.com/unicorn-utterances/social-media-posts

I think it would be great to foster a much more open community by adding into the contributing guide (which should probably be broken into a CONTRIBUTING.md file with this change) a way to make a PR in order to Tweet out the announcement for the new post

**Comment by thomaselder** [comment]
Will upcoming changes to twitter api policy affect this?

**Comment by crutchcorn** [comment]
Closing, as Twitter's API makes this impossible
