### ISSUE TITLE
Add an about us page 

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#9]
Designs provided by @tommyemo 

![about](https://user-images.githubusercontent.com/9100169/62716581-3ae8cd80-b9b7-11e9-9c30-4d601c6a7132.png)
![landing – mobile](https://user-images.githubusercontent.com/9100169/62716583-3ae8cd80-b9b7-11e9-943d-3bde47d8bafc.png)

**Comment by adueppen** [comment]
I noticed that the authors page (as in **/authors**/crutchcorn) currently doesn't exist, but it seems like it would be pretty similar to the contributors section for the about page. I'm not quite sure how we would want to structure it but it's something to keep in mind.

**Comment by crutchcorn** [comment]
I mean, we can just add an HTML redirect of `/authors` to `/aboutus#authors`, I think that would suffice

**Comment by adueppen** [comment]
Yeah I was kind of thinking about that but you have a better idea of how you want to organize the site anyway so I was going to leave it up to you.
