### ISSUE TITLE
[Website Bug]: inconsistent font size across code blocks

### ISSUE THREAD

**Issue by jocdiazm** [unicorn-utterances/unicorn-utterances#972]
### Description

Hello team ,

I’m fairly new to the website content but wanted to report a possible bug regarding font size when navigating code blocks.

### Minimal Reproduction

1. Use a browser in iOS (happens on safari and chrome)
2. Go to a post and scroll to find code blocks
3. Notice the different font sizes across them

Example [post: what is use form state and status](https://unicorn-utterances.com/posts/what-is-use-form-state-and-status)

screenshots: 

![IMG_8328](https://github.com/unicorn-utterances/unicorn-utterances/assets/13368066/71dfff4c-15cc-4679-b0ad-b818d67e2540)
![IMG_8327](https://github.com/unicorn-utterances/unicorn-utterances/assets/13368066/e486c94f-54de-436c-ac04-97e6d796af77)

### Exception or Error

None

**Comment by crutchcorn** [comment]
Thanks for reporting this! I'll have to take a look sometime in the new year to figure out what could be going on
